### ISSUE TITLE
Procedure inscription nouvel organisateur

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#1]
A fortiori,
soucis après remplissage du formulaire.
La page après remplissage du formulaire indique de contacter example@mail.com ( détail peut être )
Je reçois bien un lien de vérification mais celui n active pas le compte. Une autre validation ( via gestionnaire du site par exemple ) nécessaire ? 
le mail commence par http example.com account confirm email ( rien à voir avec le nom de domaine test

**Comment by Puyb** [comment]
Peux tu joindre une copie des mails que tu as reçu, stp...

**Comment by seblonch** [comment]
webmaster@localhost (webmaster@localhost)
Ajouter aux contacts
10:04
[Conserver ce message en haut de votre boîte de réception]
À : slbcseblon@hotmail.com
webmaster@localhost
A user on example.com has created an account using this email address.
 
 To confirm this email address, go to http://example.com/account/confirm_email/91af1d0eaf2fb9a2ecb3c1e69add082a5a6e18f8c5690b52f995fb514e7f5fa4/
 
 If you did not sign up for this site, you can ignore this message.

**Comment by seblonch** [comment]
réinscription faite et validée. 
juste changer l adresse email de contact apparaissant après validation du formulaire qui est example@mail.com
