### ISSUE TITLE
modèles mail

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#10]
![mails](https://cloud.githubusercontent.com/assets/16399614/12009801/ef223542-ac88-11e5-8776-e7ce572bb3b7.png)
juste pour faire plus zolie : 
relance_solo2 -> relance avant suppression et réatribution inscription ( modifier date dans le mail type )
relance_last	-> relance avant clôture inscription
suppression	-> suppression inscription
facture	-> facture
relance_solo	-> relance avant suppression et réatribution inscription ( modifier date dans le mail type )
change_request	-> mail d'inscription *automatique*
changement_numero_admin	-> changement numéro/catégorie ( pour organisateur ) *automatique*
changement_numero -> changement numéro/catégorie suite modification par équipe *automatique*
info_course	-> information sur la course ( modifier corps message avant envoi )
erreur	-> erreur dans l inscription ( modifier corps de message avant envoi )
inscription_admin	-> mail d'inscription automatique pour l'organisateur *automatique*
plan	-> envoi plan d'accès ( à modifier avant envoi)
paiement_admin	-> paiement reçu pour l'organisateur *automatique*
inscription -> mail d'inscription pour gérant équipe *automatique*
paiement -> mail paiement reçu et téléchargement facture *automatique*
relance -> relance pour manque de documents et/ou paiement
ajouter mail sans corps

voir aussi si j ai bien compris les messages type ;) et j ai pas vu de différence entre relance_solo et relance_solo2
possible de les reclasser en 
mail automatique sans intervention organisateur ( les *automatique* )
mail sans modification 
mail avec modifications

mettre un message d avertissement pour modifier les entêtes à la création de la course pour modifier l expéditeur ( par défaut PUC )

**Comment by Puyb** [comment]
Attention, les templates de mails pour les 6hdp sont ceux que j'avais fait les années précédentes...
Il faut que tu regarde les templates qui sont crée avec une nouvelle course (ça devrait marcher maintenant)...

De plus les nom des templates sont important sinon le système ne retrouvera pas les mails à envoyer automatiquement (les noms ne peuvent pas être changer come ça)...

**Comment by seblonch** [comment]
mince pour les noms ( ou rajouter une colonne à côté pour expliquer ce à quoi ils correspondent (uniquement dans la partie équipe alors )
pour les nouvelles courses, j arrive toujours pas à créer ( toujours le même message )

**Comment by Puyb** [comment]
Fait un F5 sur la page pour ajouter une course avant de remplir le 
formulaire, stp

Le 27/12/2015 12:19, seblonch a écrit :
>
> mince pour les noms ( ou rajouter une colonne à côté pour expliquer ce 
> à quoi ils correspondent (uniquement dans la partie équipe alors )
> pour les nouvelles courses, j arrive toujours pas à créer ( toujours 
> le même message )
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Puyb/inscriptions_roller/issues/10#issuecomment-167402353>.
>

-- 
Puyb

**Comment by seblonch** [comment]
en faisant f5, en supprimant le cache et les cookies, ça ne fonctionne toujours pas :( j ai testé sous firefox et internet explorer
