### ISSUE TITLE
inscription côté coureur

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#14]
à fortiori; ça marche
pas de soucis particulier... en même temps; base éprouvé depuis 3 ans...
juste rajouté un lien de retour vers le site d inscription dans la page de conclusion ( le lien donnée dans la partie organisation ou le lien de présentation enduroller... )
![inscription1](https://cloud.githubusercontent.com/assets/16399614/12056976/d5bdaf76-af3c-11e5-9188-1daa9060ad8b.png)

**Comment by seblonch** [comment]
pas reçu de mail reprenant les infos de mon inscription ( ni côté coureur ni côté orga

**Comment by seblonch** [comment]
je viens de recevoir un mail d inscription d une équipe ( mail auto reçu par l organisateur ) donc ça marche ;)

**Comment by Puyb** [comment]
Tu va rire : Regarde ce qu'il y avait dans le code à la ligne 622 et 623...
https://github.com/Puyb/inscriptions_roller/blob/d370a89b946000f0e8c83fb4b513f80d68af2625/inscriptions/models.py#L622

Et après, je me demandais pourquoi je recevais les mails...

**Comment by seblonch** [comment]
faut rajouter un beau "debug" ou différencier "tes" messages d erreur ( enfin ceux que tu reçois ) maintenant. Peut être voir les intitulés et compositions de tous les messages "internes" d ailleurs pour mieux les différencier
