### ISSUE TITLE
création nouvelle course

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#2]
je n arrive pas à créer de nouvelle course ( il n y a pas d indication sur l erreur : 

![testserveur1](https://cloud.githubusercontent.com/assets/16399614/11956259/396c72c6-a8b9-11e5-9281-801129f2406d.jpg)
![finde](https://cloud.githubusercontent.com/assets/16399614/11956270/407e6092-a8b9-11e5-9071-5d150d88b92d.jpg)

j ai fait plusieurs tests avant : si on oublie de remplir un des champs que tu vois rempli sur les captures d écrans, il me le marque en rouge mais là, j ai le message et pas d aide sur l erreur...

**Comment by seblonch** [comment]
problème identique avec mon compte d "origine" et celui que j ai créer y a cinq minutes

**Comment by Puyb** [comment]
Est ce que tu as eu le panneau avec les prix pour chaque catégorie avant de cliquer sur enregistrer ?

**Comment by seblonch** [comment]
tout à fait et il est préremplie donc j y ai pas touché

**Comment by Puyb** [comment]
Pas encore trouvé ce qui vas pas..  ça marche chez moi en entrant la même chose que toi... A creuser...
