### ISSUE TITLE
création course modèle de course vide

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#25]
je viens d essayer de créer une course avec le modèle vide, il m a renvoyé une erreur : 
![testaug](https://cloud.githubusercontent.com/assets/16399614/12224342/40a8d84c-b7ee-11e5-9595-463cb0c7b849.png)
la seule autre ligne non remplie est celle de la date de l augmentation de prix...

**Comment by seblonch** [comment]
on ne peux pas créer de course autrement qu en utilisant le modèle 6 heures de Paris

**Comment by seblonch** [comment]
sinon course créée sans avoir sélectionné de date d augmentation des tarifs en prenant le modèle 6h de Paris existant ( sans compte paypal renseigné aussi )

**Comment by Puyb** [comment]
Et tu as réussi à faire des inscriptions dessus ?

Le 2016-01-10
23:16, seblonch a écrit : 

> sinon course créée sans avoir sélectionné
de date d augmentation des tarifs en prenant le modèle 6h de Paris
existant ( sans compte paypal renseigné aussi ) 
> 
> --
> Reply to this
email directly or view it on GitHub [1].

 

Links:
------
[1]
https://github.com/Puyb/inscriptions_roller/issues/25#issuecomment-170399032

**Comment by seblonch** [comment]
non : 
- en tant qu organisateur, j ai eu le bandeau vert "en attente d activation" donc je ne sais pas trop la manip que tu dois faire ensuite ( j ai pas eu de mail / je ne sais pas si je dois en recevoir un en tant qu organisateur / peut être en recevoir au moins un pour signaler l activation )
- elle apparait pas sur la page enduroller.fr pour pouvoir s inscrire ( je relève le même soucis au niveau des courses tata et plop qui devraient apparaitre en tant qu anciennes courses sur la même page. )

**Comment by Puyb** [comment]
Elle est activée 

Le 2016-01-11 14:36, seblonch a écrit : 

> non :

> 
> * en tant qu organisateur, j ai eu le bandeau vert "en attente d
activation" donc je ne sais pas trop la manip que tu dois faire ensuite
( j ai pas eu de mail / je ne sais pas si je dois en recevoir un en tant
qu organisateur / peut être en recevoir au moins un pour signaler l
activation )
> * elle apparait pas sur la page enduroller.fr pour
pouvoir s inscrire ( je relève le même soucis au niveau des courses tata
et plop qui devraient apparaitre en tant qu anciennes courses sur la
même page. )
> 
> --
> Reply to this email directly or view it on GitHub
[1].

 

Links:
------
[1]
https://github.com/Puyb/inscriptions_roller/issues/25#issuecomment-170550993
