### ISSUE TITLE
mails corrects et incorrects

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#26]
juste pour info : reçu dans l ordre et contenu correct : 
- mail pour l organisateur pour signaler activation de la course.
- mail pour l orga pour les inscriptions d équipe ( essai pour solo et duo )
- mail pour responsable équipe solo validation inscription solo ( avec signalement pièce manquante
- mail pour relance solo avec pièce manquante ( licence ou certif )

reçu avec contenu non correct : 
- mail pour responsable équipe duo suite inscription : 
- manque les pièces manquantes au dossier 
- paiement de "None" euros effectué
- mail de relance pour équipe duo : 
- manque les pièces manquantes ( certif et/ou licence )
- soucis identique paiement "None" au lieu de zéro

Pour la détection des pièces manquantes, j en déduis qu il y a soucis à partir du moment où il doit en vérifier plus d une...

**Comment by Puyb** [comment]
Le 11/01/2016 16:06, seblonch a écrit :
>
> juste pour info : reçu dans l ordre et contenu correct :
>
>   * mail pour l organisateur pour signaler activation de la course
>   * mail pour l orga pour les inscriptions d équipe ( essai pour solo
>     et duo )
>   * mail pour responsable équipe solo validation inscription solo (
>     avec signalement pièce manquante
>   * mail pour relance solo avec pièce manquante ( licence ou certif )
>
> reçu avec contenu non correct :
>
>   * mail pour responsable équipe duo suite inscription :
>   * manque les pièces manquantes au dossier
>   * paiement de "None" euros effectué
>   * mail de relance pour équipe duo :
>   * manque les pièces manquantes ( certif et/ou licence )
>   * soucis identique paiement "None" au lieu de zéro
>
> Pour la détection des pièces manquantes, j en déduis qu il y a soucis 
> à partir du moment où il doit en vérifier plus d une
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Puyb/inscriptions_roller/issues/26>.
>
Peux tu me copier les mails en questions, stp...

-- 
Puyb
