### ISSUE TITLE
reception message test

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#27]
[aa22] Message
Nom: Puyb
Email: puyb@puyb.net

Test envoi mail contacts

mail reçu à 22h47 ( des fois que tu en ai envoyé d autres que j aurais pas eu )

suggestion : tu peux mettre l option automatique "répondre à" à ces mails de contact et le lier à l organisateur concerné ?
genre si c est un mail venant de la partie organisateur de Paris : répondre à organisation@6hdeparis.fr ou si c est un mail envoyé par st aignan : que la réponse auto du mail aille vers le mail de contact de st aignan )

**Comment by seblonch** [comment]
au cas où la personne répondrait sur ce mail, tu as une "messagerie" auto avec renvoi d un message d échec de contact genre : 
Les courriels envoyés à l adresse mail destinataire de votre message sont automatiquement supprimés et non lus. Merci de vous référer au premier message reçu pour avoir l adresse de votre interlocuteur. Nous nous excusons pour la gène occasionné et vous souhaitons une bonne journée

**Comment by Puyb** [comment]
c'est un message d'un patineur a l'orga... donc repondre a doit me 
repondrer a moi... Tu peux tester....



Le 12/01/2016 00:13, seblonch a écrit :
>
> au cas où la personne répondrait sur ce mail, tu as une "messagerie" 
> auto avec renvoi d un message d échec de contact genre :
> Les courriels envoyés à l adresse mail destinataire de votre message 
> sont automatiquement supprimés et non lus. Merci de vous référer au 
> premier message reçu pour avoir l adresse de votre interlocuteur. Nous 
> nous excusons pour la gène occasionné et vous souhaitons une bonne journée
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Puyb/inscriptions_roller/issues/27#issuecomment-170728425>.
>

-- 
Puyb
