### ISSUE TITLE
attribution droit nouvel utilisateur

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#3]
hop, j ai voulu attribuer des droits au compte créé aujourd hui avec celui créer l année dernière ( comme tu l as marqué dans un mail ) ... bon, je sais pas trop ou fouiner mais je suis tomber sur cette page en faisant 
- ouvrir la session sous mon compte de l année dernière
je tombe sur cette page donc je sais pas où aller ( y a rien de changer par rapport à cette année quand je clique sur la course du 02 aoùt 2015 ) 
![connection](https://cloud.githubusercontent.com/assets/16399614/11957163/3f803ff6-a8c0-11e5-86c3-52d9e422ea5b.jpg)
détail : en haut j ai marqué Administration 6h de Paris 2015; peut être qu une autre page devrait souvrir si j ai des droits d administration sur "toutes" les courses ( ou le site enduroller si tu préfères )
- demander à rejoindre l équipe d une course
- demander à rejoindre l équipe d une course

![rejoindre1](https://cloud.githubusercontent.com/assets/16399614/11957101/93aa02c0-a8bf-11e5-8032-59077ba74602.jpg)
![rejoindre2](https://cloud.githubusercontent.com/assets/16399614/11957102/93ad9f66-a8bf-11e5-801e-ea5a913d74e4.jpg)

**Comment by Puyb** [comment]
Il faut cliquer sur la course que tu veux (6hdp15), puis aller dans accreditations
