### ISSUE TITLE
liens certif / autorisation parentale dans procédure inscription

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#34]
chef chef ^^
j ai vu que les liens ( sur la page d inscription de chaque équipier ) renvoyaient ... vers rien du tout ( en gros lien mort )
- donc voir à les repointer vers quelque chose
- peut être mettre dans les caractéristiques de la course ( rentrées par l organisateur ) un mini formulaire où l organisateur mettra le lien vers lesdits certifs et autorisations parentales sil  veut faire des documents "personnalisés" pour cet event -> prévoir un document par défaut avec plein de blanc à remplir

**Comment by Puyb** [comment]
fixé en preprod
