### ISSUE TITLE
critère première ligne adresse non obligatoire

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#38]
comme marqué dans le titre : la première ligne de remplissage de l adresse ne fait pas partie des critères obligatoires => à rendre obligatoire au moins pour la personne inscrivant l équipe je pense

* peut être mettre une astérisque en face de chaque ligne obligatoire ( genre après la case ou avant car on ne le sait pas si on a rien oublié avant de valider ( confort ;) )

**Comment by Puyb** [comment]
Non, il y a des gens qui n'ont pas de première ligne d'adresse... Genre dans des très petits villages, il n'y a pas de non de rue...
