### ISSUE TITLE
mail auto inscription admin

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#40]
chef chef, j ai raté d une journée la première inscription car pas reçu de mail auto sur la boite mail de l orga :p ( perso, je vais surveiller les deux mais à voir pour les prochains )

===> un compteur d envoi de mail serait sympa car je ne sais même pas si le mail a été envoyé au gérant de l équipe

**Comment by seblonch** [comment]
par contre, je reçois le mail de paiement via paypal ( ce qui fait que j ai vu qu on avait une deuxième inscription ) :p

**Comment by Puyb** [comment]
Le mail inscription ne semble pas être envoyé... 
Je ne le vois pas dans l'historique
Tu peux essayer de t'inscrire et voir si tu le reçois, stp ? (et supprime l'inscription après ;-) )

**Comment by seblonch** [comment]
mailauto admin envoyé au responsable d équipe malgré le template disant organisateur ( constaté hier soir sur inscription équipe 1

**Comment by Puyb** [comment]
ça devrait être réglé...
