### ISSUE TITLE
page équipe pour l organisateur

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#41]
![erratumpageequpeadmin](https://cloud.githubusercontent.com/assets/16399614/23139516/0d6c1584-f7ad-11e6-9ee4-54dc443e1cc8.png)
c est sur l image : des erreurs 400 et des critères de catégorie d âge non trouvés

**Comment by Puyb** [comment]
Ce sont les explications pour la page d'inscription ;-)
Je vais voir pour les supprimer de la page d'admin...

**Comment by seblonch** [comment]
C'est pas gênant puisque cela permet de faire une piqûre de rappel en cas de question sur le dossier ( je pense aux "futurs" organisateurs) ...  Donc pas une mauvaise idée et ça gêne en rien la visibilité ou la gestion du dossier.
________________________________
De : Puyb <notifications@github.com>
Envoyé : mardi 21 février 2017 09:58:10
À : Puyb/inscriptions_roller
Cc : seblonch; Author
Objet : Re: [Puyb/inscriptions_roller] page équipe pour l organisateur (#41)


Ce sont les explications pour la page d'inscription ;-)
Je vais voir pour les supprimer de la page d'admin...
