### ISSUE TITLE
Erreur reste a payer dans retrait dossards

### ISSUE THREAD

**Issue by Puyb** [Puyb/inscriptions_roller#44]
Equipe 10, a payé 60, mais retrait dosard indique reste a payer 90

**Comment by Puyb** [comment]
Quelle course ?
Est ce qu'il n'ya pas eu un changement de date d'augmentation des tarifs ?

**Comment by seblonch** [comment]
changement de duo en trio ( enfin équipe de plus de deux, paiement sur place. inscription en duo en date du 12 ( après changement tarif  ) puis changement de catégorie.
====>>> problème soulevé des multi paiements d ailleurs car ils ne pouvaient plus payer en ligne puisque l inscription "était déjà" "rêglé" pour paypal ( mais cela n "inquiétait" pas car on demandait la différence sur place
