### ISSUE TITLE
réponses questions extra côtés admin

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#46]
* inversion des transpondeurs et tailles T Shirt sur les pages récapitulatives des équipes ( mais ok sur page d inscription )

* les questions que l on rajoute en page gérant et page finale visibles uniquement en faisant "Afficher" Autres dans la feuille de l équipe ce qui peut facilement être oublier si on vérifie pas chaque fiche et qu il y a une info "importante" ( par contre, n ayant pas forcement d interêt à savoir comment ils ont connu la course quand je vérifie le dossier, il y est "bien" )

**Comment by Puyb** [comment]
Pour le premier point, c'est une erreur que j'ai faite lors de l'importation de données sur la base de preprod. Pas gracve, ça sera bon dans la version finale..

Pour le second point, tu propose de les mettre où ?

**Comment by seblonch** [comment]
Je ne sais pas trop : en fait, cela dépendrait vraiment de ce qui est concerner...
Soit à droite du bloc commentaires en haut  ou visibles après le lien [ "Autres" Afficher ] si cela se révèle important pour l équipe concernée soit tout en bas si pas important ( en fait, en haut si on a besoin d y voir sinon en bas si ça relève des stats ou de choses qu y n impacteront pas la course en cours mais peut être les suivantes... A toi de voir le plus simple à faire

**Comment by seblonch** [comment]
après reflection et pour rester homogène, je dirais de les mettre à droite de commentaires avant gérant : 
ca reste visible et on peut mettre un commentaire en face s y référant en cas de besoin 
sauf si stats comme le moyen de connaissance de la course qui peut rester où il est
