### ISSUE TITLE
ajout équipier sur la page équipe côté admin

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#51]
en cliquant sur l onglet rajouter objet supplémentaire équipier sur la page admin, on a juste le cadre d un nouvel équipier qui apparait sans aucune info et sans moyen de le modifier 
en faisant enregistrer : rien est modifier et l équipe reste avec le même nombre d anciens équipiers

**Comment by Puyb** [comment]
Fait
