### ISSUE TITLE
export des équipes par date de naissance

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#53]
juste s il est possible de mettre un tri des équipes par date de naissances ( je pense au fait d extraire les mineurs entre autre )

**Comment by Puyb** [comment]
Tu peux le faire dans ton tableur après coup... Le but ici est de sortir les données, pas de remplacer excel... ;-)

**Comment by Puyb** [comment]
@seblonch Est ce que la réponse te convient ou est ce que je dois faire un truc ?

Si c'est OK ferme le ticket stp ;-)
