### ISSUE TITLE
adresse email hotmail, live et consorts

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#55]
possible de mettre une info bulle avec confirmation ( uniquement pour le gérant d équipe ) annoncant ( quand il s inscrit avec une adresse en hotmail ou live ( y a un troisième domaine lié qui déconne il me semble ) comme quoi : " nous avons rencontré des problèmes par le passé avec cet hébergeur de mail, vérifiez que vous recevez bien un mail dès la fin de l inscription et contactez nous le cas échéant"

**Comment by seblonch** [comment]
ou un message sur la page finish 
je continuerai à utiliser le compte gmail 6heuresdeparis mais je ne sais pas comment les autres orga gèrent ce soucis...

**Comment by Puyb** [comment]
Nouveau serveur de mail en prod depuis ce matin, plus de problèmes
