### ISSUE TITLE
Échec inscription équipe serveur test course plop

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#56]
J'ai eu ça à la place de la validation :
![screenshot_20180109-082009](https://user-images.githubusercontent.com/16399614/34722771-73a6fa00-f548-11e7-89b4-3142796a34ca.png)
![screenshot_20180109-082019](https://user-images.githubusercontent.com/16399614/34722772-73df7696-f548-11e7-9f5d-03bb4456cb5f.png)
![screenshot_20180109-082000](https://user-images.githubusercontent.com/16399614/34722773-741a500e-f548-11e7-9835-94a2d692f968.png)
![screenshot_20180109-082122](https://user-images.githubusercontent.com/16399614/34722774-7442f9c8-f548-11e7-9f20-81c7a660584c.png)
![screenshot_20180109-082053](https://user-images.githubusercontent.com/16399614/34722775-747407d4-f548-11e7-9233-7556a698bcad.png)

**Comment by Puyb** [comment]
ça devrait être réglé
