### ISSUE TITLE
Choix nombre équipier chrome Android 

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#57]
Impossible de sélectionner le nombre de équipiers en utilisant Chrome sur mon téléphone ( menu s'ouvre pas). ( même en cochant version pour ordinateur dans les options)

**Comment by seblonch** [comment]
Firefox sur Android  : le menu s'ouvre mais vide

**Comment by Puyb** [comment]
Le problème était plus grave que ça et affectait tous les navigateurs où tu n'étais pas logué en admin pour toutes les courses avec des catégories différentes des 6hdp...
Et pour celles qui avait les même catégories, les limites du nombre d'équipes par categories ne marchaient plus...

En fait, en dur dans le code, je prenais les 6hdp15 comme référence plutot que la course en cours !

Bien vu !!!
