### ISSUE TITLE
Template mail serveur test

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#59]
J'ai voulu testé l envoi de mail sur le serveur test et il m'indique une erreur de template

**Comment by Puyb** [comment]
* Quelle course ?
* Quelle équipe ?
* Quelle modèle de mail ?

Tu peux essayé d'être un peu plus spécifique dans tes rapports, stp ? N'hésites pas à mettre le maximum d'info pour que je puisse retrouver ce qui ne va pas...

**Comment by seblonch** [comment]
il m affichait aucun des template sur paris 2016 pour la dernière équipe inscrite mais c est revenu...
