### ISSUE TITLE
administration: vue des équipes: visualisation d'un paiement en erreur

### ISSUE THREAD

**Issue by luilegeant** [Puyb/inscriptions_roller#63]
Bonjour,

Urgence:
----------
Faible car il est toujours possible de voir la croix dans la case verte.

Explication:
-------------
Dans le tableau des équipes (coté administration) je visualise un paiement en erreur avec une couleur contradictoire.
![image](https://user-images.githubusercontent.com/8501519/38453929-f3d0695a-3a5d-11e8-9d94-f030e066a5cb.png)

Demande:
-----------
Serait-il possible d'avoir l'image avec un fond rouge plutôt que vert ?

Comment reproduire:
------------------------
Comment m'en suis-je rendu compte:
- j'ai ajouté une note (dans le champ détail à coté du paiement) et sauvé, 
- retour sur la fiche de l'équipe, 
- puis déplacé ma note dans le champ commentaire et sauvé. 
- Et lors du retour à la page qui liste toutes les équipes je me suis rendu compte que le carré était vert, j'attendais autre chose, mais pas du vert.

Note: le champ montant payé est toujours resté vide durant ces manipulations.

Merci

**Comment by seblonch** [comment]
![erreurpaiementsymbole](https://user-images.githubusercontent.com/16399614/47618849-1979bd80-dad8-11e8-878e-006a11241774.png)
Cela doit dépendre du navigateur ou cela a été résolu depuis...
