### ISSUE TITLE
Recherche équipes contenant des mineurs

### ISSUE THREAD

**Issue by seblonch** [Puyb/inscriptions_roller#75]
Dans la page récapitulant toutes les équipes, rajouter un filtre pour afficher toutes les équipes comprenant au moins un mineur.
Cela permettrait éventuellement de retrouver ses équipes plus facilement pour extraire les autoisations parentales ou autres documents les concernant ( idée suite mail CDRS91 sur sa question d extraction en bloc des autorisations parentales )

**Comment by Puyb** [comment]
Colonne de droite, filtre ajouté
